services:
  product:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: micsvc_product
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - db

  db:
    image: postgres:16.3
    container_name: micsvc_db
    environment:
      POSTGRES_DB: micsvc
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    network_mode: host